basePath: /
definitions:
  registry.RawYAML:
    properties:
      active:
        type: boolean
      raw:
        type: string
      version:
        type: string
    type: object
  registry.YAMLImport:
    properties:
      active:
        type: boolean
      content:
        additionalProperties: true
        type: object
      version:
        type: string
    type: object
  v1.Request:
    properties:
      name:
        type: string
    type: object
  v1.Response:
    properties:
      greeting:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Minimal Go HTTP server.
  title: Maelstrom API
  version: 1.0.0
paths:
  /:
    get:
      description: Returns hello message
      produces:
      - text/plain
      responses:
        "200":
          description: Hello, Maelstrom!
          schema:
            type: string
      summary: Root endpoint
  /api/v1/greet:
    post:
      consumes:
      - application/json
      description: Greet user by name
      parameters:
      - description: User name
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/v1.Request'
      produces:
      - application/json
      responses:
        "200":
          description: greeting
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Invalid JSON
          schema:
            type: string
        "405":
          description: Method not allowed
          schema:
            type: string
      summary: Greet user
      tags:
      - api
  /api/v1/import/{filename}:
    post:
      description: Manual import
      parameters:
      - description: Filename
        in: path
        name: filename
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Import YAML
  /api/v1/raw-yamls:
    get:
      description: List registry raw contents (unrendered)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/registry.RawYAML'
            type: array
      summary: List Raw YAMLs
  /api/v1/yamls:
    get:
      description: List registry
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/registry.YAMLImport'
            type: array
      summary: List YAMLs
swagger: "2.0"
